// Date: 8/4/2013 1:59:23 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelBurfalaunt extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
  
  public ModelBurfalaunt()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 24);
      Shape1.addBox(0F, 0F, 0F, 14, 14, 8);
      Shape1.setRotationPoint(-7F, 3F, -9F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.0698132F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(-6F, 3F, -1F, 12, 12, 12);
      Shape2.setRotationPoint(0F, 2F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, -0.0698132F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 48, 0);
      Shape3.addBox(0F, 0F, 0F, 5, 14, 5);
      Shape3.setRotationPoint(-7F, 10F, 4F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 48, 0);
      Shape3.addBox(0F, 0F, 0F, 5, 14, 5);
      Shape3.setRotationPoint(-6F, 10F, -8F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 48, 0);
      Shape3.addBox(0F, 0F, 0F, 5, 14, 5);
      Shape3.setRotationPoint(1F, 10F, -8F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 48, 0);
      Shape3.addBox(0F, 0F, 0F, 5, 14, 5);
      Shape3.setRotationPoint(2F, 10F, 4F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 16, 46);
      Shape4.addBox(0F, 0F, 0F, 8, 8, 8);
      Shape4.setRotationPoint(-4F, 6F, -14F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 48, 32);
      Shape5.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape5.setRotationPoint(-2F, 11F, -15F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 50, 30);
      Shape6.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape6.setRotationPoint(-1F, 10F, -15F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 68, 0);
      Shape7.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape7.setRotationPoint(-6F, 6F, -12F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0.5585054F);
      Shape7 = new ModelRenderer(this, 68, 0);
      Shape7.addBox(0F, -1F, 0F, 4, 1, 1);
      Shape7.setRotationPoint(6F, 6F, -12F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 2.583087F);
      Shape7 = new ModelRenderer(this, 68, 2);
      Shape7.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape7.setRotationPoint(-6F, 6F, -12F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, -1.012291F);
      Shape7 = new ModelRenderer(this, 68, 2);
      Shape7.addBox(0F, -1F, 0F, 3, 1, 1);
      Shape7.setRotationPoint(6F, 6F, -12F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, -2.164208F);
      Shape8 = new ModelRenderer(this, 0, 46);
      Shape8.addBox(0F, 0F, 0F, 4, 4, 4);
      Shape8.setRotationPoint(-2F, 8F, 9F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 54);
      Shape9.addBox(0F, 0F, 0F, 2, 2, 2);
      Shape9.setRotationPoint(-1F, 8F, 12F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0.2268928F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
