// Date: 8/4/2013 10:36:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNative extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
  
  public ModelNative()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 28, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 12, 1);
      Shape1.setRotationPoint(-4F, 13F, -3F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.2792527F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 28, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 12, 1);
      Shape1.setRotationPoint(3F, 13F, -3F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.2792527F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 20, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 10, 2);
      Shape2.setRotationPoint(-4.5F, 4F, -1F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, -0.2792527F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 20, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 10, 2);
      Shape2.setRotationPoint(2.5F, 4F, -1F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, -0.2792527F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 6, 8, 4);
      Shape3.setRotationPoint(-3F, -2F, -3F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0.1745329F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 32, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape4.setRotationPoint(-4F, 0F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, -1.658063F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 32, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape4.setRotationPoint(2F, 0F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, -1.658063F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 40, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(-4.5F, 0F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, -0.5410521F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 40, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(-3F, 0F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, -0.5410521F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 40, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(2F, 0F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, -0.5410521F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 40, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(3.5F, 0F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, -0.5410521F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 44, 0);
      Shape6.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape6.setRotationPoint(-1F, -3F, -4F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0.4712389F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 16, 13);
      Shape7.addBox(0F, 0F, 0F, 6, 1, 6);
      Shape7.setRotationPoint(-3F, -3F, -7F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0.1745329F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 16, 20);
      Shape8.addBox(0F, 0F, 0F, 5, 3, 5);
      Shape8.setRotationPoint(-2.5F, -6F, -6.5F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0.1745329F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 12);
      Shape9.addBox(0F, 0F, 0F, 3, 3, 5);
      Shape9.setRotationPoint(-1.5F, 3F, 1F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, -0.4886922F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 20);
      Shape10.addBox(0F, 0F, 0F, 2, 2, 5);
      Shape10.setRotationPoint(-1F, 5.5F, 4F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, -0.2792527F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 27);
      Shape11.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape11.setRotationPoint(-0.5F, 7F, 8F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
